name: Test

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"

jobs:

  lint:
    name: Lint
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-bandit flake8-bugbear flake8-builtins flake8-docstrings flake8-eradicate flake8-pytest-style flake8-simplify mccabe pytest
    - name: Lint with flake8
      run: |
        flake8 --exclude=test/debuggable_process.py --count --docstring-convention=numpy --max-complexity=10 --max-line-length=127 --statistics pdb_attach/*.py test/*.py

  test:
    # And type check. It's easier to do here as opposed to making a new matrix.
    name: Test
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['2.7', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Type check with Mypy
      if: ${{ matrix.python != '2.7' }}
      run: |
        python -m pip install mypy
        mypy --no-incremental -p pdb_attach
    - name: Test with pytest
      run: |
        pytest
